# Generated by Django 5.1.7 on 2025-12-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='fullscreen_exits',
            field=models.IntegerField(default=0, help_text='Number of times user exited fullscreen'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged for suspicious activity'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='tab_switches',
            field=models.IntegerField(default=0, help_text='Number of times user switched tabs'),
        ),
    ]
